import Stripe from "stripe";

export const stripe = {
  charges: {
    create: jest.fn().mockResolvedValue({
      id: "ch_3MCrtuKDSOau1RiW1b90ikRy",
      object: "charge",
      amount: 2000,
      amount_captured: 0,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: "txn_1HWWvdKDSOau1RiWzpP2va8w",
      billing_details: {
        address: {
          city: null,
          country: null,
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: null,
        name: "Jenny Rosen",
        phone: null,
      },
      calculated_statement_descriptor: null,
      captured: false,
      created: 1670535906,
      currency: "gbp",
      customer: null,
      description:
        "My First Test Charge (created for API docs at https://www.stripe.com/docs/api)",
      disputed: false,
      failure_balance_transaction: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      outcome: null,
      paid: true,
      payment_intent: null,
      payment_method: "card_1MCrtZKDSOau1RiWHMwCoM2j",
      payment_method_details: {
        card: {
          brand: "visa",
          checks: {
            address_line1_check: null,
            address_postal_code_check: null,
            cvc_check: "pass",
          },
          country: "US",
          exp_month: 8,
          exp_year: 2023,
          fingerprint: "tTw1Aq9LDpJsyoyq",
          funding: "credit",
          installments: null,
          last4: "4242",
          mandate: null,
          network: "visa",
          three_d_secure: null,
          wallet: null,
        },
        type: "card",
      },
      receipt_email: null,
      receipt_number: null,
      receipt_url:
        "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xSFc1WlJLRFNPYXUxUmlXKOK1yZwGMgYOBkSaL6w6LBbkmpyupv4jYa6t9q4RJJnD-Awq7wrsqPBSjRfklLBIHxIwsKak6bzVNzVa",
      refunded: false,
      refunds: {
        object: "list",
        data: [],
        has_more: false,
        url: "/v1/charges/ch_3MCrtuKDSOau1RiW1b90ikRy/refunds",
      },
      review: null,
      shipping: null,
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: "succeeded",
      transfer_data: null,
      transfer_group: null,
      source: "tok_mastercard",
    }),
  },
};
