name: orders-tests

on:
  pull_request:
    paths:
      - 'orders/**'
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'orders/**'


jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
